inherit_gem:
  rubocop-fjord:
    - "config/rubocop.yml"
    - "config/rails.yml"

AllCops:
  SuggestExtensions: false

Rails/LexicallyScopedActionFilter:
  Exclude:
    - app/controllers/high_voltage/pages_controller.rb
